{"name": "test_external_command", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == 'Hello from subprocess\\n'\n  - Hello from subprocess", "trace": "capsys = <_pytest.capture.CaptureFixture object at 0x7c3676adf790>\n\n>   ???\nE   AssertionError: assert '' == 'Hello from subprocess\\n'\nE     - Hello from subprocess\n\n/home/oleg/PycharmProjects/pytest_2023/tests/test_ip_address/test_ip_address.py:109: AssertionError"}, "start": 1718123091107, "stop": 1718123091108, "uuid": "0155ec7e-ca78-4ca9-933c-fcf9eeb84a53", "historyId": "6c4e034e3c49c6fbf24fe497aed53df2", "testCaseId": "6c4e034e3c49c6fbf24fe497aed53df2", "fullName": "tests.test_ip_address.test_ip_address#test_external_command", "labels": [{"name": "parentSuite", "value": "tests.test_ip_address"}, {"name": "suite", "value": "test_ip_address"}, {"name": "host", "value": "ca8132c2c276"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_ip_address.test_ip_address"}]}