{"name": "test_add_with_type_error[1-1-2]", "status": "passed", "parameters": [{"name": "x", "value": "1"}, {"name": "y", "value": "'1'"}, {"name": "res", "value": "2"}], "start": 1711624440923, "stop": 1711624440923, "uuid": "3e8412a0-46b6-4007-a708-c58ff73652e4", "historyId": "7bfcf4987460dd7ad05408552bbe17e3", "testCaseId": "c4535174573fa79997bd065240c66b58", "fullName": "tests.tests_2024.test_main.TestCalculator#test_add_with_type_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('fixture_one', 'fixture_two')"}, {"name": "parentSuite", "value": "tests.tests_2024"}, {"name": "suite", "value": "test_main"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "99f39438cbb2"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_2024.test_main"}]}