{"name": "test_failed_one", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failed_one():\n>       assert False\nE       assert False\n\ntests/hooks_example_one/test_hooks_one.py:5: AssertionError"}, "start": 1709643071243, "stop": 1709643071243, "uuid": "37a70592-80a8-4ffc-9a79-4ec7e8791af7", "historyId": "23d52723e57958adc44387c82542344f", "testCaseId": "c558f24a7332ea023994a41b3d5aa3ef", "fullName": "tests.hooks_example_one.test_hooks_one#test_failed_one", "labels": [{"name": "parentSuite", "value": "tests.hooks_example_one"}, {"name": "suite", "value": "test_hooks_one"}, {"name": "host", "value": "fisher-P55A-UD3"}, {"name": "thread", "value": "38528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.hooks_example_one.test_hooks_one"}]}